import type { ToolSlug } from "@/lib/tools";

/** Dropzone accept per tool: MIME -> extensions. */
export const CONVERT_ACCEPT: Partial<Record<ToolSlug, Record<string, string[]>>> = {
  // Image
  "avif-to-png": { "image/avif": [".avif"] },
  "avif-to-jpeg": { "image/avif": [".avif"] },
  "avif-to-webp": { "image/avif": [".avif"] },
  "webp-to-png": { "image/webp": [".webp"] },
  "webp-to-jpeg": { "image/webp": [".webp"] },
  "png-to-jpeg": { "image/png": [".png"] },
  "png-to-webp": { "image/png": [".png"] },
  "jpeg-to-png": { "image/jpeg": [".jpg", ".jpeg", ".jfif"] },
  "jpeg-to-webp": { "image/jpeg": [".jpg", ".jpeg", ".jfif"] },
  "gif-to-png": { "image/gif": [".gif"] },
  "gif-to-jpeg": { "image/gif": [".gif"] },
  "gif-to-webp": { "image/gif": [".gif"] },
  "bmp-to-png": { "image/bmp": [".bmp"] },
  "bmp-to-jpeg": { "image/bmp": [".bmp"] },
  "bmp-to-webp": { "image/bmp": [".bmp"] },
  "ico-to-png": { "image/x-icon": [".ico"], "image/vnd.microsoft.icon": [".ico"] },
  "ico-to-jpeg": { "image/x-icon": [".ico"], "image/vnd.microsoft.icon": [".ico"] },
  "ico-to-webp": { "image/x-icon": [".ico"], "image/vnd.microsoft.icon": [".ico"] },
  "tiff-to-png": { "image/tiff": [".tiff", ".tif"] },
  "tiff-to-jpeg": { "image/tiff": [".tiff", ".tif"] },
  "tiff-to-webp": { "image/tiff": [".tiff", ".tif"] },
  "apng-to-png": { "image/apng": [".apng", ".png"] },
  "apng-to-jpeg": { "image/apng": [".apng", ".png"] },
  "apng-to-webp": { "image/apng": [".apng", ".png"] },
  "svg-to-png": { "image/svg+xml": [".svg", ".svgz"] },
  "svg-to-jpeg": { "image/svg+xml": [".svg", ".svgz"] },
  "svg-to-webp": { "image/svg+xml": [".svg", ".svgz"] },
  // Audio
  "wav-to-mp3": { "audio/wav": [".wav"], "audio/wave": [".wav"] },
  "wav-to-ogg": { "audio/wav": [".wav"], "audio/wave": [".wav"] },
  "wav-to-flac": { "audio/wav": [".wav"], "audio/wave": [".wav"] },
  "wav-to-m4a": { "audio/wav": [".wav"], "audio/wave": [".wav"] },
  "wav-to-aac": { "audio/wav": [".wav"], "audio/wave": [".wav"] },
  "wav-to-opus": { "audio/wav": [".wav"], "audio/wave": [".wav"] },
  "wav-to-wma": { "audio/wav": [".wav"], "audio/wave": [".wav"] },
  "wav-to-aiff": { "audio/wav": [".wav"], "audio/wave": [".wav"] },
  "mp3-to-wav": { "audio/mpeg": [".mp3"] },
  "mp3-to-ogg": { "audio/mpeg": [".mp3"] },
  "mp3-to-flac": { "audio/mpeg": [".mp3"] },
  "mp3-to-m4a": { "audio/mpeg": [".mp3"] },
  "mp3-to-aac": { "audio/mpeg": [".mp3"] },
  "mp3-to-opus": { "audio/mpeg": [".mp3"] },
  "mp3-to-wma": { "audio/mpeg": [".mp3"] },
  "mp3-to-aiff": { "audio/mpeg": [".mp3"] },
  "ogg-to-mp3": { "audio/ogg": [".ogg", ".oga"] },
  "ogg-to-wav": { "audio/ogg": [".ogg", ".oga"] },
  "ogg-to-flac": { "audio/ogg": [".ogg", ".oga"] },
  "ogg-to-m4a": { "audio/ogg": [".ogg", ".oga"] },
  "ogg-to-aac": { "audio/ogg": [".ogg", ".oga"] },
  "ogg-to-opus": { "audio/ogg": [".ogg", ".oga"] },
  "ogg-to-wma": { "audio/ogg": [".ogg", ".oga"] },
  "ogg-to-aiff": { "audio/ogg": [".ogg", ".oga"] },
  "flac-to-mp3": { "audio/flac": [".flac"] },
  "flac-to-wav": { "audio/flac": [".flac"] },
  "flac-to-ogg": { "audio/flac": [".flac"] },
  "flac-to-m4a": { "audio/flac": [".flac"] },
  "flac-to-aac": { "audio/flac": [".flac"] },
  "flac-to-opus": { "audio/flac": [".flac"] },
  "flac-to-wma": { "audio/flac": [".flac"] },
  "flac-to-aiff": { "audio/flac": [".flac"] },
  "m4a-to-mp3": { "audio/mp4": [".m4a"], "audio/x-m4a": [".m4a"] },
  "m4a-to-wav": { "audio/mp4": [".m4a"], "audio/x-m4a": [".m4a"] },
  "m4a-to-ogg": { "audio/mp4": [".m4a"], "audio/x-m4a": [".m4a"] },
  "m4a-to-flac": { "audio/mp4": [".m4a"], "audio/x-m4a": [".m4a"] },
  "m4a-to-aac": { "audio/mp4": [".m4a"], "audio/x-m4a": [".m4a"] },
  "m4a-to-opus": { "audio/mp4": [".m4a"], "audio/x-m4a": [".m4a"] },
  "m4a-to-wma": { "audio/mp4": [".m4a"], "audio/x-m4a": [".m4a"] },
  "m4a-to-aiff": { "audio/mp4": [".m4a"], "audio/x-m4a": [".m4a"] },
  "aac-to-mp3": { "audio/aac": [".aac"], "audio/mp4": [".aac"] },
  "aac-to-wav": { "audio/aac": [".aac"], "audio/mp4": [".aac"] },
  "aac-to-ogg": { "audio/aac": [".aac"], "audio/mp4": [".aac"] },
  "aac-to-flac": { "audio/aac": [".aac"], "audio/mp4": [".aac"] },
  "aac-to-m4a": { "audio/aac": [".aac"], "audio/mp4": [".aac"] },
  "aac-to-opus": { "audio/aac": [".aac"], "audio/mp4": [".aac"] },
  "aac-to-wma": { "audio/aac": [".aac"], "audio/mp4": [".aac"] },
  "aac-to-aiff": { "audio/aac": [".aac"], "audio/mp4": [".aac"] },
  "opus-to-wav": { "audio/opus": [".opus"] },
  "opus-to-mp3": { "audio/opus": [".opus"] },
  "opus-to-ogg": { "audio/opus": [".opus"] },
  "opus-to-flac": { "audio/opus": [".opus"] },
  "opus-to-m4a": { "audio/opus": [".opus"] },
  "opus-to-aac": { "audio/opus": [".opus"] },
  "opus-to-wma": { "audio/opus": [".opus"] },
  "opus-to-aiff": { "audio/opus": [".opus"] },
  "wma-to-wav": { "audio/x-ms-wma": [".wma"] },
  "wma-to-mp3": { "audio/x-ms-wma": [".wma"] },
  "wma-to-ogg": { "audio/x-ms-wma": [".wma"] },
  "wma-to-flac": { "audio/x-ms-wma": [".wma"] },
  "wma-to-m4a": { "audio/x-ms-wma": [".wma"] },
  "wma-to-aac": { "audio/x-ms-wma": [".wma"] },
  "wma-to-opus": { "audio/x-ms-wma": [".wma"] },
  "wma-to-aiff": { "audio/x-ms-wma": [".wma"] },
  "aiff-to-wav": { "audio/aiff": [".aiff", ".aif"], "audio/x-aiff": [".aiff", ".aif"] },
  "aiff-to-mp3": { "audio/aiff": [".aiff", ".aif"], "audio/x-aiff": [".aiff", ".aif"] },
  "aiff-to-ogg": { "audio/aiff": [".aiff", ".aif"], "audio/x-aiff": [".aiff", ".aif"] },
  "aiff-to-flac": { "audio/aiff": [".aiff", ".aif"], "audio/x-aiff": [".aiff", ".aif"] },
  "aiff-to-m4a": { "audio/aiff": [".aiff", ".aif"], "audio/x-aiff": [".aiff", ".aif"] },
  "aiff-to-aac": { "audio/aiff": [".aiff", ".aif"], "audio/x-aiff": [".aiff", ".aif"] },
  "aiff-to-opus": { "audio/aiff": [".aiff", ".aif"], "audio/x-aiff": [".aiff", ".aif"] },
  "aiff-to-wma": { "audio/aiff": [".aiff", ".aif"], "audio/x-aiff": [".aiff", ".aif"] },
  // Video
  "mp4-to-webm": { "video/mp4": [".mp4"] },
  "mp4-to-mov": { "video/mp4": [".mp4"] },
  "mp4-to-mkv": { "video/mp4": [".mp4"] },
  "mp4-to-avi": { "video/mp4": [".mp4"] },
  "mp4-to-gif": { "video/mp4": [".mp4"] },
  "mp4-to-flv": { "video/mp4": [".mp4"] },
  "mp4-to-wmv": { "video/mp4": [".mp4"] },
  "mp4-to-m4v": { "video/mp4": [".mp4"] },
  "mp4-to-ogv": { "video/mp4": [".mp4"] },
  "mp4-to-3gp": { "video/mp4": [".mp4"] },
  "webm-to-mp4": { "video/webm": [".webm"] },
  "webm-to-mov": { "video/webm": [".webm"] },
  "webm-to-mkv": { "video/webm": [".webm"] },
  "webm-to-avi": { "video/webm": [".webm"] },
  "webm-to-gif": { "video/webm": [".webm"] },
  "webm-to-flv": { "video/webm": [".webm"] },
  "webm-to-wmv": { "video/webm": [".webm"] },
  "webm-to-m4v": { "video/webm": [".webm"] },
  "webm-to-ogv": { "video/webm": [".webm"] },
  "webm-to-3gp": { "video/webm": [".webm"] },
  "mov-to-mp4": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mov-to-webm": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mov-to-mkv": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mov-to-avi": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mov-to-gif": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mov-to-flv": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mov-to-wmv": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mov-to-m4v": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mov-to-ogv": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mov-to-3gp": { "video/quicktime": [".mov"], "video/mp4": [".mov"] },
  "mkv-to-mp4": { "video/x-matroska": [".mkv"] },
  "mkv-to-webm": { "video/x-matroska": [".mkv"] },
  "mkv-to-mov": { "video/x-matroska": [".mkv"] },
  "mkv-to-avi": { "video/x-matroska": [".mkv"] },
  "mkv-to-gif": { "video/x-matroska": [".mkv"] },
  "mkv-to-flv": { "video/x-matroska": [".mkv"] },
  "mkv-to-wmv": { "video/x-matroska": [".mkv"] },
  "mkv-to-m4v": { "video/x-matroska": [".mkv"] },
  "mkv-to-ogv": { "video/x-matroska": [".mkv"] },
  "mkv-to-3gp": { "video/x-matroska": [".mkv"] },
  "avi-to-mp4": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "avi-to-webm": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "avi-to-mov": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "avi-to-mkv": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "avi-to-gif": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "avi-to-flv": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "avi-to-wmv": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "avi-to-m4v": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "avi-to-ogv": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "avi-to-3gp": { "video/x-msvideo": [".avi"], "video/avi": [".avi"] },
  "gif-to-mp4": { "image/gif": [".gif"] },
  "gif-to-webm": { "image/gif": [".gif"] },
  "gif-to-mov": { "image/gif": [".gif"] },
  "gif-to-mkv": { "image/gif": [".gif"] },
  "gif-to-avi": { "image/gif": [".gif"] },
  "gif-to-flv": { "image/gif": [".gif"] },
  "gif-to-wmv": { "image/gif": [".gif"] },
  "gif-to-m4v": { "image/gif": [".gif"] },
  "gif-to-ogv": { "image/gif": [".gif"] },
  "gif-to-3gp": { "image/gif": [".gif"] },
  "flv-to-mp4": { "video/x-flv": [".flv"] },
  "flv-to-webm": { "video/x-flv": [".flv"] },
  "flv-to-mov": { "video/x-flv": [".flv"] },
  "flv-to-mkv": { "video/x-flv": [".flv"] },
  "flv-to-avi": { "video/x-flv": [".flv"] },
  "flv-to-gif": { "video/x-flv": [".flv"] },
  "flv-to-wmv": { "video/x-flv": [".flv"] },
  "flv-to-m4v": { "video/x-flv": [".flv"] },
  "flv-to-ogv": { "video/x-flv": [".flv"] },
  "flv-to-3gp": { "video/x-flv": [".flv"] },
  "wmv-to-mp4": { "video/x-ms-wmv": [".wmv"] },
  "wmv-to-webm": { "video/x-ms-wmv": [".wmv"] },
  "wmv-to-mov": { "video/x-ms-wmv": [".wmv"] },
  "wmv-to-mkv": { "video/x-ms-wmv": [".wmv"] },
  "wmv-to-avi": { "video/x-ms-wmv": [".wmv"] },
  "wmv-to-gif": { "video/x-ms-wmv": [".wmv"] },
  "wmv-to-flv": { "video/x-ms-wmv": [".wmv"] },
  "wmv-to-m4v": { "video/x-ms-wmv": [".wmv"] },
  "wmv-to-ogv": { "video/x-ms-wmv": [".wmv"] },
  "wmv-to-3gp": { "video/x-ms-wmv": [".wmv"] },
  "m4v-to-mp4": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "m4v-to-webm": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "m4v-to-mov": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "m4v-to-mkv": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "m4v-to-avi": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "m4v-to-gif": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "m4v-to-flv": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "m4v-to-wmv": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "m4v-to-ogv": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "m4v-to-3gp": { "video/x-m4v": [".m4v"], "video/mp4": [".m4v"] },
  "ogv-to-mp4": { "video/ogg": [".ogv"] },
  "ogv-to-webm": { "video/ogg": [".ogv"] },
  "ogv-to-mov": { "video/ogg": [".ogv"] },
  "ogv-to-mkv": { "video/ogg": [".ogv"] },
  "ogv-to-avi": { "video/ogg": [".ogv"] },
  "ogv-to-gif": { "video/ogg": [".ogv"] },
  "ogv-to-flv": { "video/ogg": [".ogv"] },
  "ogv-to-wmv": { "video/ogg": [".ogv"] },
  "ogv-to-m4v": { "video/ogg": [".ogv"] },
  "ogv-to-3gp": { "video/ogg": [".ogv"] },
  "3gp-to-mp4": { "video/3gpp": [".3gp"] },
  "3gp-to-webm": { "video/3gpp": [".3gp"] },
  "3gp-to-mov": { "video/3gpp": [".3gp"] },
  "3gp-to-mkv": { "video/3gpp": [".3gp"] },
  "3gp-to-avi": { "video/3gpp": [".3gp"] },
  "3gp-to-gif": { "video/3gpp": [".3gp"] },
  "3gp-to-flv": { "video/3gpp": [".3gp"] },
  "3gp-to-wmv": { "video/3gpp": [".3gp"] },
  "3gp-to-m4v": { "video/3gpp": [".3gp"] },
  "3gp-to-ogv": { "video/3gpp": [".3gp"] },
  // Document
  "merge-pdfs": { "application/pdf": [".pdf"] },
  "split-pdf": { "application/pdf": [".pdf"] },
  "docx-to-html": {
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [".docx"],
  },
};

export function getAccept(slug: ToolSlug): Record<string, string[]> | undefined {
  return CONVERT_ACCEPT[slug];
}
