export const TOOLS = [
  // ---- Image ----
  { slug: "avif-to-png", name: "AVIF to PNG", description: "Convert AVIF images to PNG in browser", category: "image", proOnly: false },
  { slug: "avif-to-jpeg", name: "AVIF to JPEG", description: "Convert AVIF to JPEG in browser", category: "image", proOnly: false },
  { slug: "avif-to-webp", name: "AVIF to WebP", description: "Convert AVIF to WebP in browser", category: "image", proOnly: false },
  { slug: "heif-to-jpg", name: "HEIF/HEIC to JPG", description: "Convert HEIF/HEIC images to JPG in browser", category: "image", proOnly: false },
  { slug: "heif-to-png", name: "HEIF/HEIC to PNG", description: "Convert HEIF/HEIC images to PNG in browser", category: "image", proOnly: false },
  { slug: "heif-to-gif", name: "HEIF/HEIC to GIF", description: "Convert HEIF/HEIC to GIF (animated if multi-frame) in browser", category: "image", proOnly: false },
  { slug: "webp-to-png", name: "WebP to PNG", description: "Convert WebP to PNG without upload", category: "image", proOnly: false },
  { slug: "webp-to-jpeg", name: "WebP to JPEG", description: "Convert WebP to JPEG locally", category: "image", proOnly: false },
  { slug: "png-to-jpeg", name: "PNG to JPEG", description: "Convert PNG to JPEG locally", category: "image", proOnly: false },
  { slug: "png-to-webp", name: "PNG to WebP", description: "Convert PNG to WebP in browser", category: "image", proOnly: false },
  { slug: "jpeg-to-png", name: "JPEG to PNG", description: "Convert JPEG images to PNG in browser", category: "image", proOnly: false },
  { slug: "jpeg-to-webp", name: "JPEG to WebP", description: "Convert JPEG to WebP in browser", category: "image", proOnly: false },
  { slug: "gif-to-png", name: "GIF to PNG", description: "Convert GIF to PNG in browser", category: "image", proOnly: false },
  { slug: "gif-to-jpeg", name: "GIF to JPEG", description: "Convert GIF to JPEG in browser", category: "image", proOnly: false },
  { slug: "gif-to-webp", name: "GIF to WebP", description: "Convert GIF to WebP in browser", category: "image", proOnly: false },
  { slug: "bmp-to-png", name: "BMP to PNG", description: "Convert BMP images to PNG in browser", category: "image", proOnly: false },
  { slug: "bmp-to-jpeg", name: "BMP to JPEG", description: "Convert BMP to JPEG in browser", category: "image", proOnly: false },
  { slug: "bmp-to-webp", name: "BMP to WebP", description: "Convert BMP to WebP in browser", category: "image", proOnly: false },
  { slug: "ico-to-png", name: "ICO to PNG", description: "Convert ICO to PNG in browser", category: "image", proOnly: false },
  { slug: "ico-to-jpeg", name: "ICO to JPEG", description: "Convert ICO to JPEG in browser", category: "image", proOnly: false },
  { slug: "ico-to-webp", name: "ICO to WebP", description: "Convert ICO to WebP in browser", category: "image", proOnly: false },
  { slug: "tiff-to-png", name: "TIFF to PNG", description: "Convert TIFF to PNG in browser", category: "image", proOnly: false },
  { slug: "tiff-to-jpeg", name: "TIFF to JPEG", description: "Convert TIFF to JPEG in browser", category: "image", proOnly: false },
  { slug: "tiff-to-webp", name: "TIFF to WebP", description: "Convert TIFF to WebP in browser", category: "image", proOnly: false },
  { slug: "apng-to-png", name: "APNG to PNG", description: "Convert APNG to PNG (first frame) in browser", category: "image", proOnly: false },
  { slug: "apng-to-jpeg", name: "APNG to JPEG", description: "Convert APNG to JPEG (first frame) in browser", category: "image", proOnly: false },
  { slug: "apng-to-webp", name: "APNG to WebP", description: "Convert APNG to WebP (first frame) in browser", category: "image", proOnly: false },
  { slug: "svg-to-png", name: "SVG to PNG", description: "Rasterize SVG to PNG in browser", category: "image", proOnly: false },
  { slug: "svg-to-jpeg", name: "SVG to JPEG", description: "Rasterize SVG to JPEG in browser", category: "image", proOnly: false },
  { slug: "svg-to-webp", name: "SVG to WebP", description: "Rasterize SVG to WebP in browser", category: "image", proOnly: false },
  // ---- Audio ----
  { slug: "wav-to-mp3", name: "WAV to MP3", description: "Convert WAV audio to MP3 locally", category: "audio", proOnly: false },
  { slug: "wav-to-ogg", name: "WAV to OGG", description: "Convert WAV to OGG in browser", category: "audio", proOnly: false },
  { slug: "wav-to-flac", name: "WAV to FLAC", description: "Convert WAV to FLAC in browser", category: "audio", proOnly: false },
  { slug: "wav-to-m4a", name: "WAV to M4A", description: "Convert WAV to M4A in browser", category: "audio", proOnly: false },
  { slug: "wav-to-aac", name: "WAV to AAC", description: "Convert WAV to AAC in browser", category: "audio", proOnly: false },
  { slug: "wav-to-opus", name: "WAV to Opus", description: "Convert WAV to Opus in browser", category: "audio", proOnly: false },
  { slug: "wav-to-wma", name: "WAV to WMA", description: "Convert WAV to WMA in browser", category: "audio", proOnly: false },
  { slug: "wav-to-aiff", name: "WAV to AIFF", description: "Convert WAV to AIFF in browser", category: "audio", proOnly: false },
  { slug: "mp3-to-wav", name: "MP3 to WAV", description: "Convert MP3 to WAV audio in browser", category: "audio", proOnly: false },
  { slug: "mp3-to-ogg", name: "MP3 to OGG", description: "Convert MP3 to OGG in browser", category: "audio", proOnly: false },
  { slug: "mp3-to-flac", name: "MP3 to FLAC", description: "Convert MP3 to FLAC in browser", category: "audio", proOnly: false },
  { slug: "mp3-to-m4a", name: "MP3 to M4A", description: "Convert MP3 to M4A in browser", category: "audio", proOnly: false },
  { slug: "mp3-to-aac", name: "MP3 to AAC", description: "Convert MP3 to AAC in browser", category: "audio", proOnly: false },
  { slug: "mp3-to-opus", name: "MP3 to Opus", description: "Convert MP3 to Opus in browser", category: "audio", proOnly: false },
  { slug: "mp3-to-wma", name: "MP3 to WMA", description: "Convert MP3 to WMA in browser", category: "audio", proOnly: false },
  { slug: "mp3-to-aiff", name: "MP3 to AIFF", description: "Convert MP3 to AIFF in browser", category: "audio", proOnly: false },
  { slug: "ogg-to-mp3", name: "OGG to MP3", description: "Convert OGG audio to MP3", category: "audio", proOnly: false },
  { slug: "ogg-to-wav", name: "OGG to WAV", description: "Convert OGG to WAV in browser", category: "audio", proOnly: false },
  { slug: "ogg-to-flac", name: "OGG to FLAC", description: "Convert OGG to FLAC in browser", category: "audio", proOnly: false },
  { slug: "ogg-to-m4a", name: "OGG to M4A", description: "Convert OGG to M4A in browser", category: "audio", proOnly: false },
  { slug: "ogg-to-aac", name: "OGG to AAC", description: "Convert OGG to AAC in browser", category: "audio", proOnly: false },
  { slug: "ogg-to-opus", name: "OGG to Opus", description: "Convert OGG to Opus in browser", category: "audio", proOnly: false },
  { slug: "ogg-to-wma", name: "OGG to WMA", description: "Convert OGG to WMA in browser", category: "audio", proOnly: false },
  { slug: "ogg-to-aiff", name: "OGG to AIFF", description: "Convert OGG to AIFF in browser", category: "audio", proOnly: false },
  { slug: "flac-to-mp3", name: "FLAC to MP3", description: "Convert FLAC to MP3 in browser", category: "audio", proOnly: false },
  { slug: "flac-to-wav", name: "FLAC to WAV", description: "Convert FLAC to WAV in browser", category: "audio", proOnly: false },
  { slug: "flac-to-ogg", name: "FLAC to OGG", description: "Convert FLAC to OGG in browser", category: "audio", proOnly: false },
  { slug: "flac-to-m4a", name: "FLAC to M4A", description: "Convert FLAC to M4A in browser", category: "audio", proOnly: false },
  { slug: "flac-to-aac", name: "FLAC to AAC", description: "Convert FLAC to AAC in browser", category: "audio", proOnly: false },
  { slug: "flac-to-opus", name: "FLAC to Opus", description: "Convert FLAC to Opus in browser", category: "audio", proOnly: false },
  { slug: "flac-to-wma", name: "FLAC to WMA", description: "Convert FLAC to WMA in browser", category: "audio", proOnly: false },
  { slug: "flac-to-aiff", name: "FLAC to AIFF", description: "Convert FLAC to AIFF in browser", category: "audio", proOnly: false },
  { slug: "m4a-to-mp3", name: "M4A to MP3", description: "Convert M4A to MP3 in browser", category: "audio", proOnly: false },
  { slug: "m4a-to-wav", name: "M4A to WAV", description: "Convert M4A to WAV in browser", category: "audio", proOnly: false },
  { slug: "m4a-to-ogg", name: "M4A to OGG", description: "Convert M4A to OGG in browser", category: "audio", proOnly: false },
  { slug: "m4a-to-flac", name: "M4A to FLAC", description: "Convert M4A to FLAC in browser", category: "audio", proOnly: false },
  { slug: "m4a-to-aac", name: "M4A to AAC", description: "Convert M4A to AAC in browser", category: "audio", proOnly: false },
  { slug: "m4a-to-opus", name: "M4A to Opus", description: "Convert M4A to Opus in browser", category: "audio", proOnly: false },
  { slug: "m4a-to-wma", name: "M4A to WMA", description: "Convert M4A to WMA in browser", category: "audio", proOnly: false },
  { slug: "m4a-to-aiff", name: "M4A to AIFF", description: "Convert M4A to AIFF in browser", category: "audio", proOnly: false },
  { slug: "aac-to-mp3", name: "AAC to MP3", description: "Convert AAC to MP3 in browser", category: "audio", proOnly: false },
  { slug: "aac-to-wav", name: "AAC to WAV", description: "Convert AAC to WAV in browser", category: "audio", proOnly: false },
  { slug: "aac-to-ogg", name: "AAC to OGG", description: "Convert AAC to OGG in browser", category: "audio", proOnly: false },
  { slug: "aac-to-flac", name: "AAC to FLAC", description: "Convert AAC to FLAC in browser", category: "audio", proOnly: false },
  { slug: "aac-to-m4a", name: "AAC to M4A", description: "Convert AAC to M4A in browser", category: "audio", proOnly: false },
  { slug: "aac-to-opus", name: "AAC to Opus", description: "Convert AAC to Opus in browser", category: "audio", proOnly: false },
  { slug: "aac-to-wma", name: "AAC to WMA", description: "Convert AAC to WMA in browser", category: "audio", proOnly: false },
  { slug: "aac-to-aiff", name: "AAC to AIFF", description: "Convert AAC to AIFF in browser", category: "audio", proOnly: false },
  { slug: "opus-to-wav", name: "Opus to WAV", description: "Convert Opus to WAV in browser", category: "audio", proOnly: false },
  { slug: "opus-to-mp3", name: "Opus to MP3", description: "Convert Opus to MP3 in browser", category: "audio", proOnly: false },
  { slug: "opus-to-ogg", name: "Opus to OGG", description: "Convert Opus to OGG in browser", category: "audio", proOnly: false },
  { slug: "opus-to-flac", name: "Opus to FLAC", description: "Convert Opus to FLAC in browser", category: "audio", proOnly: false },
  { slug: "opus-to-m4a", name: "Opus to M4A", description: "Convert Opus to M4A in browser", category: "audio", proOnly: false },
  { slug: "opus-to-aac", name: "Opus to AAC", description: "Convert Opus to AAC in browser", category: "audio", proOnly: false },
  { slug: "opus-to-wma", name: "Opus to WMA", description: "Convert Opus to WMA in browser", category: "audio", proOnly: false },
  { slug: "opus-to-aiff", name: "Opus to AIFF", description: "Convert Opus to AIFF in browser", category: "audio", proOnly: false },
  { slug: "wma-to-wav", name: "WMA to WAV", description: "Convert WMA to WAV in browser", category: "audio", proOnly: false },
  { slug: "wma-to-mp3", name: "WMA to MP3", description: "Convert WMA to MP3 in browser", category: "audio", proOnly: false },
  { slug: "wma-to-ogg", name: "WMA to OGG", description: "Convert WMA to OGG in browser", category: "audio", proOnly: false },
  { slug: "wma-to-flac", name: "WMA to FLAC", description: "Convert WMA to FLAC in browser", category: "audio", proOnly: false },
  { slug: "wma-to-m4a", name: "WMA to M4A", description: "Convert WMA to M4A in browser", category: "audio", proOnly: false },
  { slug: "wma-to-aac", name: "WMA to AAC", description: "Convert WMA to AAC in browser", category: "audio", proOnly: false },
  { slug: "wma-to-opus", name: "WMA to Opus", description: "Convert WMA to Opus in browser", category: "audio", proOnly: false },
  { slug: "wma-to-aiff", name: "WMA to AIFF", description: "Convert WMA to AIFF in browser", category: "audio", proOnly: false },
  { slug: "aiff-to-wav", name: "AIFF to WAV", description: "Convert AIFF to WAV in browser", category: "audio", proOnly: false },
  { slug: "aiff-to-mp3", name: "AIFF to MP3", description: "Convert AIFF to MP3 in browser", category: "audio", proOnly: false },
  { slug: "aiff-to-ogg", name: "AIFF to OGG", description: "Convert AIFF to OGG in browser", category: "audio", proOnly: false },
  { slug: "aiff-to-flac", name: "AIFF to FLAC", description: "Convert AIFF to FLAC in browser", category: "audio", proOnly: false },
  { slug: "aiff-to-m4a", name: "AIFF to M4A", description: "Convert AIFF to M4A in browser", category: "audio", proOnly: false },
  { slug: "aiff-to-aac", name: "AIFF to AAC", description: "Convert AIFF to AAC in browser", category: "audio", proOnly: false },
  { slug: "aiff-to-opus", name: "AIFF to Opus", description: "Convert AIFF to Opus in browser", category: "audio", proOnly: false },
  { slug: "aiff-to-wma", name: "AIFF to WMA", description: "Convert AIFF to WMA in browser", category: "audio", proOnly: false },
  // ---- Video ----
  { slug: "mp4-to-webm", name: "MP4 to WebM", description: "Convert MP4 video to WebM in browser", category: "video", proOnly: false },
  { slug: "mp4-to-mov", name: "MP4 to MOV", description: "Convert MP4 to MOV in browser", category: "video", proOnly: false },
  { slug: "mp4-to-mkv", name: "MP4 to MKV", description: "Convert MP4 to MKV in browser", category: "video", proOnly: false },
  { slug: "mp4-to-avi", name: "MP4 to AVI", description: "Convert MP4 to AVI in browser", category: "video", proOnly: false },
  { slug: "mp4-to-gif", name: "MP4 to GIF", description: "Convert MP4 to GIF in browser", category: "video", proOnly: false },
  { slug: "mp4-to-flv", name: "MP4 to FLV", description: "Convert MP4 to FLV in browser", category: "video", proOnly: false },
  { slug: "mp4-to-wmv", name: "MP4 to WMV", description: "Convert MP4 to WMV in browser", category: "video", proOnly: false },
  { slug: "mp4-to-m4v", name: "MP4 to M4V", description: "Convert MP4 to M4V in browser", category: "video", proOnly: false },
  { slug: "mp4-to-ogv", name: "MP4 to OGV", description: "Convert MP4 to OGV in browser", category: "video", proOnly: false },
  { slug: "mp4-to-3gp", name: "MP4 to 3GP", description: "Convert MP4 to 3GP in browser", category: "video", proOnly: false },
  { slug: "webm-to-mp4", name: "WebM to MP4", description: "Convert WebM to MP4 in browser", category: "video", proOnly: false },
  { slug: "webm-to-mov", name: "WebM to MOV", description: "Convert WebM to MOV in browser", category: "video", proOnly: false },
  { slug: "webm-to-mkv", name: "WebM to MKV", description: "Convert WebM to MKV in browser", category: "video", proOnly: false },
  { slug: "webm-to-avi", name: "WebM to AVI", description: "Convert WebM to AVI in browser", category: "video", proOnly: false },
  { slug: "webm-to-gif", name: "WebM to GIF", description: "Convert WebM to GIF in browser", category: "video", proOnly: false },
  { slug: "webm-to-flv", name: "WebM to FLV", description: "Convert WebM to FLV in browser", category: "video", proOnly: false },
  { slug: "webm-to-wmv", name: "WebM to WMV", description: "Convert WebM to WMV in browser", category: "video", proOnly: false },
  { slug: "webm-to-m4v", name: "WebM to M4V", description: "Convert WebM to M4V in browser", category: "video", proOnly: false },
  { slug: "webm-to-ogv", name: "WebM to OGV", description: "Convert WebM to OGV in browser", category: "video", proOnly: false },
  { slug: "webm-to-3gp", name: "WebM to 3GP", description: "Convert WebM to 3GP in browser", category: "video", proOnly: false },
  { slug: "mov-to-mp4", name: "MOV to MP4", description: "Convert MOV to MP4 in browser", category: "video", proOnly: false },
  { slug: "mov-to-webm", name: "MOV to WebM", description: "Convert MOV to WebM in browser", category: "video", proOnly: false },
  { slug: "mov-to-mkv", name: "MOV to MKV", description: "Convert MOV to MKV in browser", category: "video", proOnly: false },
  { slug: "mov-to-avi", name: "MOV to AVI", description: "Convert MOV to AVI in browser", category: "video", proOnly: false },
  { slug: "mov-to-gif", name: "MOV to GIF", description: "Convert MOV to GIF in browser", category: "video", proOnly: false },
  { slug: "mov-to-flv", name: "MOV to FLV", description: "Convert MOV to FLV in browser", category: "video", proOnly: false },
  { slug: "mov-to-wmv", name: "MOV to WMV", description: "Convert MOV to WMV in browser", category: "video", proOnly: false },
  { slug: "mov-to-m4v", name: "MOV to M4V", description: "Convert MOV to M4V in browser", category: "video", proOnly: false },
  { slug: "mov-to-ogv", name: "MOV to OGV", description: "Convert MOV to OGV in browser", category: "video", proOnly: false },
  { slug: "mov-to-3gp", name: "MOV to 3GP", description: "Convert MOV to 3GP in browser", category: "video", proOnly: false },
  { slug: "mkv-to-mp4", name: "MKV to MP4", description: "Convert MKV to MP4 in browser", category: "video", proOnly: false },
  { slug: "mkv-to-webm", name: "MKV to WebM", description: "Convert MKV to WebM in browser", category: "video", proOnly: false },
  { slug: "mkv-to-mov", name: "MKV to MOV", description: "Convert MKV to MOV in browser", category: "video", proOnly: false },
  { slug: "mkv-to-avi", name: "MKV to AVI", description: "Convert MKV to AVI in browser", category: "video", proOnly: false },
  { slug: "mkv-to-gif", name: "MKV to GIF", description: "Convert MKV to GIF in browser", category: "video", proOnly: false },
  { slug: "mkv-to-flv", name: "MKV to FLV", description: "Convert MKV to FLV in browser", category: "video", proOnly: false },
  { slug: "mkv-to-wmv", name: "MKV to WMV", description: "Convert MKV to WMV in browser", category: "video", proOnly: false },
  { slug: "mkv-to-m4v", name: "MKV to M4V", description: "Convert MKV to M4V in browser", category: "video", proOnly: false },
  { slug: "mkv-to-ogv", name: "MKV to OGV", description: "Convert MKV to OGV in browser", category: "video", proOnly: false },
  { slug: "mkv-to-3gp", name: "MKV to 3GP", description: "Convert MKV to 3GP in browser", category: "video", proOnly: false },
  { slug: "avi-to-mp4", name: "AVI to MP4", description: "Convert AVI to MP4 in browser", category: "video", proOnly: false },
  { slug: "avi-to-webm", name: "AVI to WebM", description: "Convert AVI to WebM in browser", category: "video", proOnly: false },
  { slug: "avi-to-mov", name: "AVI to MOV", description: "Convert AVI to MOV in browser", category: "video", proOnly: false },
  { slug: "avi-to-mkv", name: "AVI to MKV", description: "Convert AVI to MKV in browser", category: "video", proOnly: false },
  { slug: "avi-to-gif", name: "AVI to GIF", description: "Convert AVI to GIF in browser", category: "video", proOnly: false },
  { slug: "avi-to-flv", name: "AVI to FLV", description: "Convert AVI to FLV in browser", category: "video", proOnly: false },
  { slug: "avi-to-wmv", name: "AVI to WMV", description: "Convert AVI to WMV in browser", category: "video", proOnly: false },
  { slug: "avi-to-m4v", name: "AVI to M4V", description: "Convert AVI to M4V in browser", category: "video", proOnly: false },
  { slug: "avi-to-ogv", name: "AVI to OGV", description: "Convert AVI to OGV in browser", category: "video", proOnly: false },
  { slug: "avi-to-3gp", name: "AVI to 3GP", description: "Convert AVI to 3GP in browser", category: "video", proOnly: false },
  { slug: "gif-to-mp4", name: "GIF to MP4", description: "Convert GIF to MP4 video", category: "video", proOnly: false },
  { slug: "gif-to-webm", name: "GIF to WebM", description: "Convert GIF to WebM in browser", category: "video", proOnly: false },
  { slug: "gif-to-mov", name: "GIF to MOV", description: "Convert GIF to MOV in browser", category: "video", proOnly: false },
  { slug: "gif-to-mkv", name: "GIF to MKV", description: "Convert GIF to MKV in browser", category: "video", proOnly: false },
  { slug: "gif-to-avi", name: "GIF to AVI", description: "Convert GIF to AVI in browser", category: "video", proOnly: false },
  { slug: "gif-to-flv", name: "GIF to FLV", description: "Convert GIF to FLV in browser", category: "video", proOnly: false },
  { slug: "gif-to-wmv", name: "GIF to WMV", description: "Convert GIF to WMV in browser", category: "video", proOnly: false },
  { slug: "gif-to-m4v", name: "GIF to M4V", description: "Convert GIF to M4V in browser", category: "video", proOnly: false },
  { slug: "gif-to-ogv", name: "GIF to OGV", description: "Convert GIF to OGV in browser", category: "video", proOnly: false },
  { slug: "gif-to-3gp", name: "GIF to 3GP", description: "Convert GIF to 3GP in browser", category: "video", proOnly: false },
  { slug: "flv-to-mp4", name: "FLV to MP4", description: "Convert FLV to MP4 in browser", category: "video", proOnly: false },
  { slug: "flv-to-webm", name: "FLV to WebM", description: "Convert FLV to WebM in browser", category: "video", proOnly: false },
  { slug: "flv-to-mov", name: "FLV to MOV", description: "Convert FLV to MOV in browser", category: "video", proOnly: false },
  { slug: "flv-to-mkv", name: "FLV to MKV", description: "Convert FLV to MKV in browser", category: "video", proOnly: false },
  { slug: "flv-to-avi", name: "FLV to AVI", description: "Convert FLV to AVI in browser", category: "video", proOnly: false },
  { slug: "flv-to-gif", name: "FLV to GIF", description: "Convert FLV to GIF in browser", category: "video", proOnly: false },
  { slug: "flv-to-wmv", name: "FLV to WMV", description: "Convert FLV to WMV in browser", category: "video", proOnly: false },
  { slug: "flv-to-m4v", name: "FLV to M4V", description: "Convert FLV to M4V in browser", category: "video", proOnly: false },
  { slug: "flv-to-ogv", name: "FLV to OGV", description: "Convert FLV to OGV in browser", category: "video", proOnly: false },
  { slug: "flv-to-3gp", name: "FLV to 3GP", description: "Convert FLV to 3GP in browser", category: "video", proOnly: false },
  { slug: "wmv-to-mp4", name: "WMV to MP4", description: "Convert WMV to MP4 in browser", category: "video", proOnly: false },
  { slug: "wmv-to-webm", name: "WMV to WebM", description: "Convert WMV to WebM in browser", category: "video", proOnly: false },
  { slug: "wmv-to-mov", name: "WMV to MOV", description: "Convert WMV to MOV in browser", category: "video", proOnly: false },
  { slug: "wmv-to-mkv", name: "WMV to MKV", description: "Convert WMV to MKV in browser", category: "video", proOnly: false },
  { slug: "wmv-to-avi", name: "WMV to AVI", description: "Convert WMV to AVI in browser", category: "video", proOnly: false },
  { slug: "wmv-to-gif", name: "WMV to GIF", description: "Convert WMV to GIF in browser", category: "video", proOnly: false },
  { slug: "wmv-to-flv", name: "WMV to FLV", description: "Convert WMV to FLV in browser", category: "video", proOnly: false },
  { slug: "wmv-to-m4v", name: "WMV to M4V", description: "Convert WMV to M4V in browser", category: "video", proOnly: false },
  { slug: "wmv-to-ogv", name: "WMV to OGV", description: "Convert WMV to OGV in browser", category: "video", proOnly: false },
  { slug: "wmv-to-3gp", name: "WMV to 3GP", description: "Convert WMV to 3GP in browser", category: "video", proOnly: false },
  { slug: "m4v-to-mp4", name: "M4V to MP4", description: "Convert M4V to MP4 in browser", category: "video", proOnly: false },
  { slug: "m4v-to-webm", name: "M4V to WebM", description: "Convert M4V to WebM in browser", category: "video", proOnly: false },
  { slug: "m4v-to-mov", name: "M4V to MOV", description: "Convert M4V to MOV in browser", category: "video", proOnly: false },
  { slug: "m4v-to-mkv", name: "M4V to MKV", description: "Convert M4V to MKV in browser", category: "video", proOnly: false },
  { slug: "m4v-to-avi", name: "M4V to AVI", description: "Convert M4V to AVI in browser", category: "video", proOnly: false },
  { slug: "m4v-to-gif", name: "M4V to GIF", description: "Convert M4V to GIF in browser", category: "video", proOnly: false },
  { slug: "m4v-to-flv", name: "M4V to FLV", description: "Convert M4V to FLV in browser", category: "video", proOnly: false },
  { slug: "m4v-to-wmv", name: "M4V to WMV", description: "Convert M4V to WMV in browser", category: "video", proOnly: false },
  { slug: "m4v-to-ogv", name: "M4V to OGV", description: "Convert M4V to OGV in browser", category: "video", proOnly: false },
  { slug: "m4v-to-3gp", name: "M4V to 3GP", description: "Convert M4V to 3GP in browser", category: "video", proOnly: false },
  { slug: "ogv-to-mp4", name: "OGV to MP4", description: "Convert OGV to MP4 in browser", category: "video", proOnly: false },
  { slug: "ogv-to-webm", name: "OGV to WebM", description: "Convert OGV to WebM in browser", category: "video", proOnly: false },
  { slug: "ogv-to-mov", name: "OGV to MOV", description: "Convert OGV to MOV in browser", category: "video", proOnly: false },
  { slug: "ogv-to-mkv", name: "OGV to MKV", description: "Convert OGV to MKV in browser", category: "video", proOnly: false },
  { slug: "ogv-to-avi", name: "OGV to AVI", description: "Convert OGV to AVI in browser", category: "video", proOnly: false },
  { slug: "ogv-to-gif", name: "OGV to GIF", description: "Convert OGV to GIF in browser", category: "video", proOnly: false },
  { slug: "ogv-to-flv", name: "OGV to FLV", description: "Convert OGV to FLV in browser", category: "video", proOnly: false },
  { slug: "ogv-to-wmv", name: "OGV to WMV", description: "Convert OGV to WMV in browser", category: "video", proOnly: false },
  { slug: "ogv-to-m4v", name: "OGV to M4V", description: "Convert OGV to M4V in browser", category: "video", proOnly: false },
  { slug: "ogv-to-3gp", name: "OGV to 3GP", description: "Convert OGV to 3GP in browser", category: "video", proOnly: false },
  { slug: "3gp-to-mp4", name: "3GP to MP4", description: "Convert 3GP to MP4 in browser", category: "video", proOnly: false },
  { slug: "3gp-to-webm", name: "3GP to WebM", description: "Convert 3GP to WebM in browser", category: "video", proOnly: false },
  { slug: "3gp-to-mov", name: "3GP to MOV", description: "Convert 3GP to MOV in browser", category: "video", proOnly: false },
  { slug: "3gp-to-mkv", name: "3GP to MKV", description: "Convert 3GP to MKV in browser", category: "video", proOnly: false },
  { slug: "3gp-to-avi", name: "3GP to AVI", description: "Convert 3GP to AVI in browser", category: "video", proOnly: false },
  { slug: "3gp-to-gif", name: "3GP to GIF", description: "Convert 3GP to GIF in browser", category: "video", proOnly: false },
  { slug: "3gp-to-flv", name: "3GP to FLV", description: "Convert 3GP to FLV in browser", category: "video", proOnly: false },
  { slug: "3gp-to-wmv", name: "3GP to WMV", description: "Convert 3GP to WMV in browser", category: "video", proOnly: false },
  { slug: "3gp-to-m4v", name: "3GP to M4V", description: "Convert 3GP to M4V in browser", category: "video", proOnly: false },
  { slug: "3gp-to-ogv", name: "3GP to OGV", description: "Convert 3GP to OGV in browser", category: "video", proOnly: false },
  // ---- Document ----
  { slug: "pdf-to-images", name: "PDF to Images", description: "Extract PDF pages as images (Pro)", category: "document", proOnly: true },
  { slug: "images-to-pdf", name: "Images to PDF", description: "Combine images into one PDF (Pro)", category: "document", proOnly: true },
  { slug: "html-to-pdf", name: "HTML to PDF", description: "Convert HTML content to PDF in browser", category: "document", proOnly: false },
  { slug: "merge-pdfs", name: "Merge PDFs", description: "Combine multiple PDFs into one", category: "document", proOnly: false },
  { slug: "split-pdf", name: "Split PDF", description: "Split PDF into one file per page", category: "document", proOnly: false },
  { slug: "docx-to-html", name: "DOCX to HTML", description: "Convert Word document to HTML", category: "document", proOnly: false },
  { slug: "text-to-docx", name: "Text to DOCX", description: "Create Word document from title and paragraphs", category: "document", proOnly: false },
  { slug: "epub-to-mobi", name: "EPUB to MOBI / AZW3", description: "Extract EPUB to HTML for Calibre (MOBI/AZW3), 100% local", category: "document", proOnly: false },
  { slug: "mobi-to-epub", name: "MOBI to EPUB", description: "Convert MOBI or AZW3 to EPUB e-book in browser, 100% local", category: "document", proOnly: false },
  { slug: "pdf-to-docx", name: "PDF to Word (DOCX)", description: "Convert PDF to DOCX in browser, no upload", category: "document", proOnly: false },
  { slug: "pdf-to-epub", name: "PDF to EPUB", description: "Convert PDF to EPUB e-book in browser", category: "document", proOnly: false },
  { slug: "length-converter", name: "Length Converter", description: "Convert meters, feet, miles, km, inches — 100% local", category: "units", proOnly: false },
  { slug: "miles-to-km", name: "Miles to Km", description: "Convert miles ↔ kilometers — 100% local", category: "units", proOnly: false },
  { slug: "feet-to-meters", name: "Feet to Meters", description: "Convert feet ↔ meters — 100% local", category: "units", proOnly: false },
  { slug: "inches-to-cm", name: "Inches to cm", description: "Convert inches ↔ centimeters — 100% local", category: "units", proOnly: false },
  { slug: "nautical-miles-to-km", name: "Nautical Miles to Km", description: "Convert nautical miles ↔ kilometers — 100% local", category: "units", proOnly: false },
  { slug: "weight-converter", name: "Weight Converter", description: "Convert kg, lb, oz, grams — 100% local", category: "units", proOnly: false },
  { slug: "pounds-to-kg", name: "Pounds to Kg", description: "Convert pounds ↔ kilograms — 100% local", category: "units", proOnly: false },
  { slug: "ounces-to-grams", name: "Ounces to Grams", description: "Convert ounces ↔ grams — 100% local", category: "units", proOnly: false },
  { slug: "stone-to-kg", name: "Stone to Kg", description: "Convert stone ↔ kilograms — 100% local", category: "units", proOnly: false },
  { slug: "jin-to-kg", name: "Jin (市斤) to Kg", description: "Convert jin (Chinese catty) ↔ kilograms — 100% local", category: "units", proOnly: false },
  { slug: "temperature-converter", name: "Temperature Converter", description: "Convert Celsius, Fahrenheit, Kelvin — 100% local", category: "units", proOnly: false },
  { slug: "fahrenheit-to-celsius", name: "Fahrenheit to Celsius", description: "Convert Fahrenheit ↔ Celsius — 100% local", category: "units", proOnly: false },
  { slug: "fahrenheit-to-kelvin", name: "Fahrenheit to Kelvin", description: "Convert Fahrenheit ↔ Kelvin — 100% local", category: "units", proOnly: false },
  { slug: "celsius-to-kelvin", name: "Celsius to Kelvin", description: "Convert Celsius ↔ Kelvin — 100% local", category: "units", proOnly: false },
  { slug: "currency-converter", name: "Currency Converter", description: "Convert USD, EUR, CNY, JPY with live rates", category: "units", proOnly: false },
  { slug: "data-storage-converter", name: "Data Storage Converter", description: "Convert bytes, KB, MB, GB, TB — 100% local", category: "data", proOnly: false },
  { slug: "time-converter", name: "Time Converter", description: "Unix timestamp, date, seconds to hours/days — 100% local", category: "units", proOnly: false },
  { slug: "cooking-units-converter", name: "Cooking Units Converter", description: "Convert cups, ml, tsp, tbsp, oz — 100% local", category: "units", proOnly: false },
  { slug: "area-converter", name: "Area Converter", description: "Convert sq m, sq ft, acres, hectares, sq miles — 100% local", category: "units", proOnly: false },
  { slug: "sqft-to-sqm", name: "Sq Ft to Sq M", description: "Convert square feet ↔ square meters — 100% local", category: "units", proOnly: false },
  { slug: "acres-to-hectares", name: "Acres to Hectares", description: "Convert acres ↔ hectares — 100% local", category: "units", proOnly: false },
  { slug: "sqmi-to-sqkm", name: "Sq Miles to Sq Km", description: "Convert square miles ↔ square kilometers — 100% local", category: "units", proOnly: false },
  { slug: "volume-converter", name: "Volume Converter", description: "Convert liters, gallons, pints, cubic feet — 100% local", category: "units", proOnly: false },
  { slug: "gallons-to-liters", name: "Gallons to Liters", description: "Convert US gallons ↔ liters — 100% local", category: "units", proOnly: false },
  { slug: "pints-to-ml", name: "Pints to mL", description: "Convert US pints ↔ milliliters — 100% local", category: "units", proOnly: false },
  { slug: "cubic-feet-to-cubic-meters", name: "Cubic Ft to Cubic M", description: "Convert cubic feet ↔ cubic meters — 100% local", category: "units", proOnly: false },
  { slug: "speed-converter", name: "Speed Converter", description: "Convert km/h, mph, knots, m/s, Mach — 100% local", category: "units", proOnly: false },
  { slug: "mph-to-kmh", name: "MPH to Km/h", description: "Convert miles per hour ↔ km/h — 100% local", category: "units", proOnly: false },
  { slug: "knots-to-kmh", name: "Knots to Km/h", description: "Convert knots ↔ km/h — 100% local", category: "units", proOnly: false },
  { slug: "mach-to-kmh", name: "Mach to Km/h", description: "Convert Mach (sea level) ↔ km/h — 100% local", category: "units", proOnly: false },
] as const;

export type ToolSlug = (typeof TOOLS)[number]["slug"];
